services:
  db:
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  init_db:
    image: poto-init-db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
    depends_on:
      db:
        condition: service_started
    command: python manage.py migrate
  add_teams:
    image: poto-add-teams
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
    depends_on:
      init_db:
        condition: service_completed_successfully
    command: python manage.py add_teams
  web:
    image: poto
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
    volumes:
      - ./win:/app/win
    ports:
      - 8080:8080
    depends_on:
      add_teams:
        condition: service_completed_successfully
